service: aws-node-nuevo # NOTE: update this with your service name

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  iam:
    role: arn:aws:iam::710271936972:role/Lambda-permisos

functions:
  hello:
    handler: handler.hello
